name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "jiong-lin@live.com"
          git config --local user.name "klmmlk"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "Keep writing documents now..."
          git push
